language: ruby
rvm:
  - 2.3.0
addons:
  postgresql: "9.4"
services:
  - redis-server
env:
  - DB=postgresql
gemfile:
  - Gemfile
before_script:
  - psql -c 'create database gofriends_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rake db:create db:migrate db:test:prepare
  - bundle exec rspec spec
